import React from "react";

const Head = () => {
  return (
    <>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="public/images/bookit_logo.png" />
    </>
  );
};

export default Head;
